sudo: false
language: ruby
rvm:
  - '2.2.6'
  - '2.3.3'
  - '2.4.0'
  - 'jruby-1.7.26'
  - 'jruby-9.0.5.0'
  - 'jruby-9.1.5.0'
install: gem install rspec ffi
script: rake
matrix:
  include:
    - os: osx
      rvm: '2.3.3'
    - os: osx
      rvm: '2.4.0'
